development:
  adapter: mysql2
  encoding: utf8
  database: educam_dev
  pool: 5
  username: root
  password:
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: educam_test
  pool: 5
  username: root
  password:
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: educam_prod
  pool: 5
  username: educam
  password: educamLancasterMySQL
  port: 3306
